### ISSUE TITLE
[rendering] boss-level feature: migrating geometries

### ISSUE THREAD

**Issue by ohmec** [ohmec/ohmec#113]
It has always been envisioned (OK, in my head anyway) to have a high-challenge snazzy feature of "migrating geometries". Putting this out there just to get it out of my head and into an issue.

To explain: take the situation of the US State of Virginia. It existed at one point as a merge of current Kentucky, West Virginia, and Virginia. In two successive steps, those states were ceded and Virginia shrunk to its current geometry. This is a non-migrating geometry change. On one day, it contained "three states worth", then the next day, "two states worth", then a subsequent date: one. Ie. very discrete changes.

Now take the situation of the growth of the Roman Empire under Augustus. There are no discrete dates, the empire just grows. (Rightly speaking: given the confidence of the accuracy of records in the 1st century BC, the empire appears to grow amorphously across time as the conquests into the frontiers ebb.) This could be considered a "migrating geometry".

Similarly, literally migratory indigenous tribes have slow-moving amorphous changes to their center of gravity.

While rendering these two types (non-migratory and migratory geometries) one would want a way to visualize these differently. Using the current viewport terminology, the `Advance` button would want to advance a percentage of the way from one geometry to another. This would allow a way to designate a "start of migration" geometry and an "end of migration" geometry, and the rendering tool would manage the morph from the first to the second, based upon where in time the current display is. So, using the Augustus example, there could be a geometry for "Roman Empire in 31BC", then another in 19BC, and the advance button would morph between the two during the time crawl. There would need to be some way in the database to link these two geometries.

It is a "boss-level" feature because it would be complex to render cleanly, especially around coastlines. But might work better for indigenous tribes which currently only designate borderless-areas.

**Comment by warrenjp** [comment]
This makes sense. One way to do this is to establish a "maximum time period between displayed migrations" so that migratory geometries display smooth migrations. For example, if this maximum time period is set to ten years, toggling Step+ (or running Advance) will jump to the next chronological database entry, unless it is more than ten years beyond the current map date, in which case the next Step will be ten years later. This will require the code to calculate changes to migration geometries at every Step, whether that Step is forward ten years or forward less than ten years due to a non-migratory database entry being less than ten years from the current map date.

My intuition is that this is worth trying, but we will have to be alert to the computation cost and rendering time. It may turn out that this solution has too great of a negative impact on platform performance.

**Comment by ohmec** [comment]
Here's what this might look like for a label-only feature. Note this is just a mock-up, might look better or worse depending upon coding.

![OlmecLabelAnimation](https://user-images.githubusercontent.com/84106593/139598159-6cc78b63-c155-4b30-a2d0-35233bf414d7.gif)

**Comment by ohmec** [comment]
I actually have a workable solution that is pretty performant (afaict), but has limitations. PR coming tonight or tomorrow.
